### ISSUE TITLE
TomEE does not stage web and web-servlet-2 applications properly

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry-community/tomee-buildpack#14]
Based on our system tests, the TomEE container does not appear to stage the `web` and `web-servlet-2` [Java Test Applications](https://github.com/cloudfoundry/java-test-applications) properly.  This needs to be fixed up.

**Comment by glyn** [comment]
See https://www.pivotaltracker.com/story/show/116541279 for work on this issue.

**Comment by glyn** [comment]
Could not reproduce the problem.
