### ISSUE TITLE
Feature Request: TomEE buildpack needs to support the deployment of ear files

### ISSUE THREAD

**Issue by kelapure** [cloudfoundry-community/tomee-buildpack#16]
A number of existing JavaEE enterprise applications are packaged as ear files. In order to replatform these applications using the TomEE buildpack onto Cloud Foundry the TomEE buildpack needs to support the `cf push` of ear files.

Underlying runtime TomEE itself supports the deployment of ear files. See http://tomee.apache.org/deploying-in-tomee.html

There is no reason we should force developers to repackage their apps as war files in order to run on TomEE in CloudFoundry

**Comment by nebhale** [comment]
EAR files encourage the running of multiple applications locally with one another in a single container.  This leads to issue as these applications are no longer independently scalable from one another.  This concern is same reason that we do not support multiple WARs in the same container in the Java Buidlacpk.  As this violates one of the primary principles of the TomEE buildpack, we do not plan to implement it.

**Comment by nebhale** [comment]
Resolved via #19
