### ISSUE TITLE
Creating resources.xml is broken

### ISSUE THREAD

**Issue by bijukunjummen** [cloudfoundry-community/tomee-buildpack#18]
I think the process of creating the resources.xml may be broken, the properties are being injected with some of the fields being null - only the jdbcUrl appears to be populated, username, scheme, password etc is null. 

For eg. consider an application bound to mysql database, the following properties are returned via the resources.xml file:

```
JtaManaged=true
JdbcDriver=org.mariadb.jdbc.Driver
JdbcUrl=jdbc:mysql://server:3306/instance?user=auser&password=apwed
UserName=null
Password=null
PasswordCipher=PlainText
OpenEJBResourceClasspath=false
TestOnBorrow=true
ValidationQuery=SELECT 1
```

This leads to an error of the following type:

```
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Access denied for user 'vcap'@'10.254.0.6' (using password: NO)
2017-05-01T18:27:32.28-0700 [APP/PROC/WEB/0] OUT        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:571)
2017-05-01T18:27:32.28-0700 [APP/PROC/WEB/0] OUT        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:503)
2017-05-01T18:27:32.28-0700 [APP/PROC/WEB/0] OUT        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:382)
2017-05-01T18:27:32.28-0700 [APP/PROC/WEB/0] OUT        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:839)
```

This can be traced back to the spring-cloud-connector libraries which sets only the JDBCUrl and not the other fields - https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-cloudfoundry-connector/src/main/java/org/springframework/cloud/cloudfoundry/RelationalServiceInfoCreator.java#L74

**Comment by SvetlinZarev** [comment]
Hi,

The resource-configuration feature [1]  does not work that way. It creates a very simple resource.xml and registers a property provider [2] which provides the datasource properties during runtime. So is it possible that you've manually provided some pre-populated resource.xml ?

[1] https://github.com/cloudfoundry-community/tomee-buildpack-resource-configuration
[2] https://rmannibucau.wordpress.com/2014/09/15/tomee-resource-properties-provider-one-more-step/

Kind regards,
Svetlin

**Comment by violetagg** [comment]
Hi,

> only the jdbcUrl appears to be populated, username, scheme, password etc is null.

Isn't this information populated by the driver's implementation using the provided URL?
https://github.com/MariaDB/mariadb-connector-j/blob/1.5.9/src/main/java/org/mariadb/jdbc/internal/protocol/AbstractConnectProtocol.java#L145

Regards,
Violeta

**Comment by bijukunjummen** [comment]
Thanks @SvetlinZarev, @violetagg , yes I understand that the creds(password, username, jdbcUrl) is delegated to a provider and generated at runtime, I just put the final generated values(I have forked the tomee-resources-configuration to print the generated values). 

I think you are right @violetagg, it should have been resolved from the jdbcUrl itself and the username, password ignored..will look a little more into that today and let you know if I see something more.

These are my steps:

`cf create-service p-myqsl 512mb mydb`
`cf bind-service myapp mydb` 
and then started up the app.

**Comment by anwarchk** [comment]
@bijukunjummen resolving from the jdbc url is what we also talked about y'day. We can look in further today.

**Comment by violetagg** [comment]
Hi,

Do you still see this problem or the issue can be closed?

Thanks,
Violeta

**Comment by bijukunjummen** [comment]
Still seeing the issue @violetagg, I haven't tried binding to anything other than mysql but mysql does have this issue.

**Comment by kelapure** [comment]
I am seeing this issue too .. here is my apphttps://github.com/kelapure/transactions

This is my app's env
```json
"cleardb": [
   {
    "credentials": {
     "hostname": "us-cdbr-iron-east-03.cleardb.net",
     "jdbcUrl": "jdbc:mysql://us-cdbr-iron-east-03.cleardb.net/ad_f7896d9afbe4a05?user=b9940cf8c3e761\u0026password=66361358",
     "name": "ad_f7896d9afbe4a05",
     "password": "66361358",
     "port": "3306",
     "uri": "mysql://b9940cf8c3e761:66361358@us-cdbr-iron-east-03.cleardb.net:3306/ad_f7896d9afbe4a05?reconnect=true",
     "username": "b9940cf8c3e761"
    },
```
Error from the TomEE Runtime
```java
017-05-11T15:48:47.18-0400 [APP/PROC/WEB/0] OUT java.sql.SQLInvalidAuthorizationSpecException: Could not connect: Access denied for user 'vcap'@'10.81.158.249' (using password: NO)
2017-05-11T15:48:47.18-0400 [APP/PROC/WEB/0] OUT [CONTAINER] .tomee.jdbc.TomEEDataSourceCreator$TomEEDataSource SEVERE  Can't create DataSource
2017-05-11T15:48:47.18-0400 [APP/PROC/WEB/0] OUT        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.throwException(ExceptionMapper.java:92)
```

**Comment by bijukunjummen** [comment]
I think I found the reason for this behavior @kelapure, @violetagg, @SvetlinZarev, @anwarchk  - it turns out that we are using an older version of [spring-cloud-connectors](https://github.com/spring-cloud/spring-cloud-connectors), v 1.2.0.RELEASE, instead of v 1.2.4.RELEASE. The behavior in [1.2.0.RELEASE of RelationalServiceInfoCreator](https://github.com/spring-cloud/spring-cloud-connectors/blob/v1.2.0.RELEASE/spring-cloud-cloudfoundry-connector/src/main/java/org/springframework/cloud/cloudfoundry/RelationalServiceInfoCreator.java) is to NOT look at the `uri` part of the credential json if `jdbcUrl` is present, whereas with [1.2.4.RELEASE of RelationalServiceInfoCreator](https://github.com/spring-cloud/spring-cloud-connectors/blob/v1.2.4.RELEASE/spring-cloud-cloudfoundry-connector/src/main/java/org/springframework/cloud/cloudfoundry/RelationalServiceInfoCreator.java) the behavior is to look at `uri` if present over `jdbcUrl`. 

The fix to this issue will be in [tomee-buildpack-resource-configuration](https://github.com/cloudfoundry-community/tomee-buildpack-resource-configuration) to pull in 1.2.4.RELEASE of spring-cloud-connectors

**Comment by nebhale** [comment]
[Done](https://github.com/cloudfoundry-community/tomee-buildpack-resource-configuration/commit/ebd7b9f63985cecc4287e63921a861291b4a1e9d) and released as `1.3.0.RELEASE`.

**Comment by bijukunjummen** [comment]
Awesome, thanks @nebhale, the update to cloud-connectors should fix the issue

**Comment by bijukunjummen** [comment]
Confirming that the change works. Thanks
