### ISSUE TITLE
jndi resources configuration should look for additional criteria - along with "relational" tag

### ISSUE THREAD

**Issue by bijukunjummen** [cloudfoundry-community/tomee-buildpack#21]
Tomee resource configuration depends on bound services having a "relational" tag for their entries to be added in as tomee created JNDI resources(resources.xml file). It will be great if additional ways of detecting if a bound service is a relational service is considered. 

For eg, if you were to create a User provided relational service it is not possible to add a tag at all and hence no entry is added into the resources.xml file. 

Additional criteria could be:

* Checking for known schema names - `mysql`, `oracle`, `db2` etc.
* Checking for `jdbc:`

**Comment by violetagg** [comment]
Look at this comment
https://github.com/cloudfoundry/cloud_controller_ng/issues/451#issuecomment-152193591

**Comment by bijukunjummen** [comment]
Thanks @violetagg, yes following the spring cloud connectors set of criteria sounds great. Will attempt a PR.

**Comment by nebhale** [comment]
Closing in lieu of #22
