### ISSUE TITLE
Unable to Read JNDI value from Birt report

### ISSUE THREAD

**Issue by salexstephen** [cloudfoundry-community/tomee-buildpack#25]
I am working on migrating Websphere application in to cloud foundry using tomee buildpack. In Websphere, the birt report read the JNDI data source to generate the report. 
Similarly, i added the JNDI entries in the resources.xml file and added the resource ref entries in the web.xml file. The birt report unable to read the JNDI entry and throwing exception in tomee buildpack. 
Do i need to add any additional configuration for birt report?

**Comment by violetagg** [comment]
Hi,

Can you provide some sample of the configuration that you need to add for birt report?
Also please provide the exception that is thrown.

Regards,
Violeta

**Comment by violetagg** [comment]
Closing as there isn't any response from the author.
