### ISSUE TITLE
Need to know if ear support is provided in TomEE buildpack

### ISSUE THREAD

**Issue by purush123** [cloudfoundry-community/tomee-buildpack#26]
Can you let me know if ear support is provided by TomEE buildpack. In my case, it is 2 war files packaged into an ear.

**Comment by violetagg** [comment]
Hi,

Yes take a look here
https://github.com/cloudfoundry-community/tomee-buildpack/blob/master/docs/container-tomee.md#support-for-deploying-an-ear-enterprise-application-archive-file

Regards,
Violeta
