### ISSUE TITLE
Generic Loading of Resources

### ISSUE THREAD

**Issue by tom-collings** [cloudfoundry-community/tomee-buildpack#28]
The current implementation allows for the loading of JDBC resources based on the contents of the bound services.  It would be nice if we could generically create resources using the property lists features, so that if we had a bound service like

```{
    "credentials": {
     "class-name": "org.cloudfoundry.test.MyType",
     "id": "someId",
     "includeInResources": "true",
     "name1": "val1",
     "name2": "val2"
    },
    "label": "user-provided",
    "name": "my-test-resource",
    "syslog_drain_url": "",
    "tags": [],
    "volume_mounts": []
   }
```

it could create a resource like

```
<Resource class-name='org.cloudfoundry.test.MyType' id='someId'>
  name1 = val1
  name2 = val2
</Resource>
```

This has the advantage of allowing customers to use non-JDBC resources as well as custom resources.

**Comment by violetagg** [comment]
Fixed by #33
