### ISSUE TITLE
 Auto-reconfiguration of Resources for TomEE

### ISSUE THREAD

**Issue by kelapure** [cloudfoundry-community/tomee-buildpack#5]
**Problem**:
Today configuration of cloud foundry backing services in TomEE is cumbersome. If I want to use postgres, I need to specify the following in my resources.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <!--
    mainly a tomee.xml embed in the application
    (META-INF or WEB-INF)
  -->
  <Resource id="jdbc/DefaultDB" type="DataSource">
      JdbcDriver org.postgresql.Driver
      JdbcUrl = jdbc:postgres://rohit:blahblahblah@9.89.203.244:4980/ilovejets
      UserName rohit
      Password blahblahblah
      JtaManaged true
  </Resource>
</resources>
```

An the following in my persistence.xml
```xml
<jta-data-source>jdbc/DefaultDB</jta-data-source>
```

_Where the URL is the one that I will have when I bind a postgres service and the name of the datasource in resources.xml and persistence.xml must be one and the same._

**Solution**:
Modifications to the tomee Buildpack that provide facilities for automatically configuring as much of the resources.xml file for tomee as possible in order to remove as much of the busywork from app migration as possible.

The buildpack will perform all of this automatic configuration by interpreting the data it finds in the VCAP_SERVICES environment variable that is configured automatically by Cloud Foundry via either brokered services or user-provided services. 

**User Story**
As a developer I would like to have a mechanism that will automatically configure the tomee server in Cloud Foundry with the bound services.

**Implementation Details**
This can be achieved with [ServiceProvider](http://tomee.apache.org/concepts.html) mechanism in TomEE. 

One possible solution would be to carry out all of the automatic configuration work based on user-provided services (often simply called "cups"), with the underlying assumption being that managed brokered services imply a level of green-field preparation that allows application developers to consume the VCAP_SERVICES environment variables directly or through libraries like Spring Boot.

**Comment by violetagg** [comment]
More information about application resources in TomEE
http://tomee.apache.org/application-resources.html

**Comment by violetagg** [comment]
Hi,

Let me describe the possible solutions [1]:
1) Generation of 'Resource' elements for resources.xml

    <Resource id="DB" type="DataSource">
      JdbcDriver  com.mysql.jdbc.Driver
      JdbcUrl     jdbc:mysql://localhost/test
      UserName    test
      Password    password
    </Resource>

Cons:
- Storing sensitive information on the file system.
- XML generation

2) Generation of system properties 

    p.setProperty("DB", "new://Resource?type=DataSource");
    p.setProperty("DB.JdbcDriver", "com.mysql.jdbc.Driver");
    p.setProperty("DB,JdbcUrl", "jdbc:mysql://localhost/test");
    p.setProperty("DB.UserName", "test");
    p.setProperty("DB.Password", "password");

This is very similar to the auto-reconfiguration for play framework where system properties are generated.
Cons:
- Storing sensitive information as system properties
- Generation of too many system properties

3) Introducing a custom Service Provider

Custom Service Provider will know how to create the resource and how to configure it.
It is described in the xml/system property using 'provider' attribute. Or another option is to introduce a lifecycle listener (Tomcat specific) that can add the Service Provider programmatically.
Cons: If it is added programmatically, implementation depends on Tomcat/Tomee internal implementation.

4) Hook in the JNDI directly
Cons: Implementation depends on Tomcat/Tomee internal implementation.

5) Mixture between 2) and 3)
Generation of a system property of type:

    DB=new://Resource?type=DataSource&properties-provider=org.cloudfoundry.reconfiguration.tomee.TomeePropertiesResourceProvider

where a custom Properties Resource Provider [2] will be used to provide the configuration.
This is very similar to the auto-reconfiguration for play framework where system properties are generated.

My preference is 5).
What do you think?

Regards,
Violeta

[1] http://tomee.apache.org/application-resources.html
[2] https://github.com/apache/tomee/blob/tomee-1.7.x/container/openejb-api/src/main/java/org/apache/openejb/api/resource/PropertiesResourceProvider.java

**Comment by nebhale** [comment]
5 looks good to me.

**Comment by kelapure** [comment]
Violeta,

I agree that 3 (CloudFoundryResourcePropertiesProvider) is the best way to generate resource definitions for TomEE. This can be vendored into the TomEE build pack similar to the java-bueldpack-support <https://github.com/cloudfoundry/java-buildpack-support.git> repo that provides logging.  The Resource Provider will be triggered via an User Provided Service. UPS will allow the flexibility to contain JDBC or MQ or WebService resources and won’t lock us into specific managed services/resource types. The ResourcePropertiesProvider will work only for TomEE. A standard compliant way of generating and injecting JavaEE resources at startup is worth investigating ...

All java based buildpacks have their own proprietary XML files (server.xml, standalone.xml, resources.xml etc) so the way in which the parsed VCAP data manifests itself will be different, but I think it would be fantastic if we could agree on some sort of standard meaning that is derived from VCAP so that the intent of someone's UPSs can be universally understood across buildpacks. In other words, a JDBC data source is a JDBC data source, and generally requires the same amount of metadata regardless of which server container you're using to define said JDBC data source. It would be useful if the shape of a UPS that represents a JDBC data source intent would be the same or similar across the buildpacks.

The support for tags on user-provided services would allow users to declare this intent rather than use use an arbitrary field in their credentials payload to indicate a JDBC UPS. They could simply tag the UPS as jdbc and then the buildpack could then expect a certain level of supporting metadata. We will need a PR to Cloud Foundry to support this.[GH-Issue <https://github.com/cloudfoundry/cloud_controller_ng/issues/451>]

I don't expect customers to be jumping from BP to BP enough so that they would expect their UPS definitions to just magically work everywhere, I like the notion of consistency, rather than having multiple buildpacks each solve the exact same problem in unique, seemingly conflicting ways. 

-cheers,
Rohit Kelapure

**Comment by violetagg** [comment]
Hi,

Please find here [1] [2] an initial implementation that handles "relational" services.

One note as this proposal implements option 5) - TomEE expects to find DB drivers in TomEE-Home/lib instead of webapp-home/WEB-INF/lib. [2]

In the implementation [1] there are properties providers for some of the "relational" services. However new properties providers can be added via java services.

Also the implementation uses tags information (as Rohit proposed) to take the "relational" services only.

I would like to discuss this proposal before continuing with the additional functionality.

Regards,
Violeta

[1] https://github.com/violetagg/tomee-buildpack-resource-configuration
[2] https://github.com/violetagg/tomee-buildpack/commit/f237fb7bb8eab5338cab4ae199633b386070b27a

**Comment by nebhale** [comment]
@violetagg I've looked everything over and only have two comments.  First, we're a Maven group, so the `resource-configuration` stuff will need to change, but no rush on that at the moment.  Second, there's no real provision for getting the DB drivers into the `<container>/lib` directory since only an application (packaging the proper drivers) is available to us.  How do you propose to get the drivers into the proper location for the JNDI loading?  (As a side note, this is why container-managed services suck...)

**Comment by violetagg** [comment]
@nebhale 
> Second, there's no real provision for getting the DB drivers into the <container>/lib 

I've moved the additional libraries link to the TomEE lib https://github.com/violetagg/tomee-buildpack/blob/resources/lib/java_buildpack/container/tomee/tomee_instance.rb (row 31)

Do you mean some other use case?

> First, we're a Maven group, so the resource-configuration stuff will need to change

I'll change from Gradle to Maven n.p.

Is there an appropriate git repository for an example application that will demonstrate this new functionality?

Thanks,
Violeta

**Comment by nebhale** [comment]
Additional libraries are only contributed by the components of the buildpack.  So, if the user packages the MySQL JDBC JAR, that won't get included in the `@droplet.additional_libraries.link_to` command and therefore end up in the wrong class loader.

Test applications go into `cloudfoundry/java-test-applications`.

**Comment by nebhale** [comment]
Also, the `cloudfoundry/java-buildpack-auto-reconfiguration` repo can give you an idea of the Maven POM we use.

**Comment by violetagg** [comment]
Here is [1] a "mavenized" version for tomee-resource-configuration project

I used a newer version for maven-shade-plugin. There is no need of ant execution at least for this project.

[1] https://github.com/violetagg/tomee-buildpack-resource-configuration/tree/maven

**Comment by violetagg** [comment]
About linking the drivers. Actually we can leave them in the WEB-INF/lib and specify them by defining a  classpath for the resource [1]:

    "new://Resource?type=DataSource&classpath=/path/to/driverVersionOne.jar"

What do you think?

http://tomee.apache.org/configuring-datasources-in-tests.html

**Comment by nebhale** [comment]
The Mavenization looks good.  I'm a bit wary of trying to tie JARs in `WEB-INF/lib` to specific services.  Do you think it can be done reliably?

**Comment by violetagg** [comment]
I started a discussion in TomEE users list about resources and configurations: http://tomee-openejb.979440.n4.nabble.com/Resource-and-UseAppClassLoader-question-td4677073.html

**Comment by violetagg** [comment]
Hello,

Let me summarize the findings till now.

Using system properties: we will create 'global' resources that require drivers to be located in the TomEE's classloader and not in the web app's classloader.
This is a limitation because the application will not be able to supply drivers with its binaries.

With 'classpath' attribute we can specify the drivers' location but if we know them which is not the case so this option does not give us a real solution.

If we relace the system property

    DB=new://Resource?type=DataSource&properties-provider=org.cloudfoundry.reconfiguration.tomee.DelegatingPropertiesProvider

with the declaration below in resources.xml

    <resources>
      <Resource id=DB type=DataSource properties-provider=org.cloudfoundry.reconfiguration.tomee.DelegatingPropertiesProvider
    </resources>

and then provide the resources.xml in the web app's WEB-INF folder we can achieve our goal - the resources will be local i.e. only for this web application and TomEE will use the web application's classloader to load the drivers. The sensitive data will not be stored on the FS but provided by the properties provider.

The repositories with the latest proposal are [1] and [2]

What do you think?

Regards,
Violeta

[1] https://github.com/violetagg/tomee-buildpack/commit/ec763e7abb400ba9de4246dc29838e9ffd2fcc8f
[2] https://github.com/violetagg/tomee-buildpack-resource-configuration/commit/5b329637cc732e2976af123be3bff23dac20a22a

**Comment by nebhale** [comment]
@violetagg I think that's a great compromise.  In general we try to avoid mucking about in the actual application uploaded by the user, but this is the perfect point at which we would.  Eliminating the global nature of the last strategy is right on.

What else do you think needs to be done to bring this to deliverable quality?

**Comment by violetagg** [comment]
The proposed implementation is supplied with tests, only documentation and example application are missing.

**Comment by nebhale** [comment]
Then I'd say you've got a green light.  Let's fill in the gaps and we'll work on getting it merged in.

**Comment by violetagg** [comment]
Where will we host the git repository for TomEE BP resource configuration?

**Comment by nebhale** [comment]
`cloudfoundry-community`.  Keep it in it's current location and once you think it's ready, we can transfer it using the GitHub transfer functionality.

**Comment by violetagg** [comment]
Here is the TomEE BP Resources Auto Configutation
https://github.com/violetagg/tomee-buildpack-resource-configuration/tree/maven

**Comment by violetagg** [comment]
I think we can close this one.

**Comment by nebhale** [comment]
Looks good to me.
